/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_app1_fingerprintjni */

#ifndef _Included_com_example_app1_fingerprintjni
#define _Included_com_example_app1_fingerprintjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_app1_fingerprintjni
 * Method:    fingerprint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_app1_fingerprintjni_fingerprint
  (JNIEnv *, jobject);

/*
 * Class:     com_example_app1_fingerprintjni
 * Method:    check
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_app1_fingerprintjni_check
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
